//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseMonitorV4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_main_dbEntities : DbContext
    {
        public siixsem_main_dbEntities()
            : base("name=siixsem_main_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getAllModels_Result> getAllModels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllModels_Result>("getAllModels");
        }
    
        public virtual ObjectResult<getLaserModels_Result> getLaserModels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLaserModels_Result>("getLaserModels");
        }
    
        public virtual ObjectResult<Nullable<int>> getStep(Nullable<int> idModel)
        {
            var idModelParameter = idModel.HasValue ?
                new ObjectParameter("idModel", idModel) :
                new ObjectParameter("idModel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getStep", idModelParameter);
        }
    }
}
