//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseMonitorV4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_laser_traceability_dbEntities : DbContext
    {
        public siixsem_laser_traceability_dbEntities()
            : base("name=siixsem_laser_traceability_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<siixsem_cgs_route_t> siixsem_cgs_route_t { get; set; }
        public virtual DbSet<siixsem_release_info_t> siixsem_release_info_t { get; set; }
    
        public virtual ObjectResult<getCgsDetails_Result> getCgsDetails(Nullable<int> id_model)
        {
            var id_modelParameter = id_model.HasValue ?
                new ObjectParameter("id_model", id_model) :
                new ObjectParameter("id_model", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCgsDetails_Result>("getCgsDetails", id_modelParameter);
        }
    }
}
