//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseMonitorV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_cgs_route_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_cgs_route_t()
        {
            this.siixsem_release_info_t = new HashSet<siixsem_release_info_t>();
        }
    
        public int id { get; set; }
        public int se_id_model { get; set; }
        public string cgs_route { get; set; }
        public string cgs_revision { get; set; }
        public System.DateTime creation_date { get; set; }
        public string cgs_pn { get; set; }
        public int valid { get; set; }
        public string pokayoke { get; set; }
        public string pair_fg_name { get; set; }
        public int isMit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_release_info_t> siixsem_release_info_t { get; set; }
    }
}
