//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseMonitorV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_release_info_t
    {
        public int id { get; set; }
        public int id_cgs_route { get; set; }
        public Nullable<int> dj_no { get; set; }
        public string dj_group { get; set; }
        public int release_qty { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime modification_date { get; set; }
    
        public virtual siixsem_cgs_route_t siixsem_cgs_route_t { get; set; }
    }
}
